# Generated by Django 4.2.5 on 2023-09-14 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_domain',
            fields=[
                ('users_domain_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('school_id', models.UUIDField(default=uuid.uuid4)),
                ('school_name', models.CharField(max_length=50)),
                ('school_code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.JSONField()),
                ('gender', models.CharField(max_length=50)),
                ('profile_pic', models.CharField(max_length=250)),
                ('roll_no', models.CharField(max_length=50)),
                ('badge', models.BigIntegerField()),
                ('superbadge', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('branch_id', models.UUIDField(default=uuid.uuid4)),
                ('branch_name', models.CharField(max_length=50)),
                ('batch_id', models.UUIDField(default=uuid.uuid4)),
                ('batch', models.CharField(max_length=50)),
                ('department_id', models.UUIDField(default=uuid.uuid4)),
                ('department_name', models.CharField(max_length=50)),
                ('degree_id', models.UUIDField(default=uuid.uuid4)),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
    ]
