# Generated by Django 4.2.5 on 2023-09-15 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_domain',
            name='badge',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='batch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='branch_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='degree_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='department_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='department_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='phone',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='profile_pic',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='roll_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='school_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='superbadge',
            field=models.BigIntegerField(default=0),
        ),
    ]
