# Generated by Django 4.2.5 on 2023-09-15 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_students',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('c_id', models.UUIDField(default=uuid.uuid4)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('badge', models.BigIntegerField(default=0)),
                ('superbadge', models.BigIntegerField(default=0)),
                ('penalty_points', models.BigIntegerField(default=0)),
                ('course_completion', models.FloatField(default=0)),
                ('last_viewed', models.DateField(null=True)),
                ('branch_id', models.UUIDField(default=uuid.uuid4)),
                ('department_id', models.UUIDField(default=uuid.uuid4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_tests',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('c_id', models.UUIDField(default=uuid.uuid4)),
                ('school_id', models.UUIDField(default=uuid.uuid4)),
                ('c_type', models.CharField(max_length=50, null=True)),
                ('branch_id', models.UUIDField(default=uuid.uuid4)),
                ('t_type', models.CharField(blank=True, max_length=50)),
                ('t_name', models.CharField(max_length=50, null=True)),
                ('c_name', models.CharField(max_length=50, null=True)),
                ('t_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('Module_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_ppa_profiles',
            fields=[
                ('s_profile_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('school_id', models.UUIDField(default=uuid.uuid4)),
                ('tenth_marks', models.FloatField(null=True)),
                ('is_tenth_percentage', models.IntegerField(null=True)),
                ('twelfth_marks', models.FloatField(null=True)),
                ('is_twelfth_percentage', models.IntegerField(null=True)),
                ('diploma_marks', models.FloatField(null=True)),
                ('is_diploma_percentage', models.IntegerField(null=True)),
                ('ug_marks', models.FloatField(null=True)),
                ('is_ug_percentage', models.IntegerField(null=True)),
                ('pg_marks', models.FloatField(null=True)),
                ('is_pg_percentage', models.IntegerField(null=True)),
                ('roll_no', models.CharField(max_length=50, null=True)),
                ('backlogs', models.IntegerField(null=True)),
                ('current_backlogs', models.IntegerField(null=True)),
                ('degree', models.CharField(max_length=50, null=True)),
                ('work_experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='badge',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='batch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='branch_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='degree_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='department_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='department_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='phone',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='profile_pic',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='roll_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='school_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='superbadge',
            field=models.BigIntegerField(default=0),
        ),
    ]
