# Generated by Django 4.2.5 on 2023-09-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_students_course_tests_student_ppa_profiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_modules',
            fields=[
                ('c_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50, null=True)),
                ('Module_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('c_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
