# Generated by Django 4.2.5 on 2023-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_domain_badge_alter_users_domain_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_domain',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='phone',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users_domain',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
