# Generated by Django 4.2.5 on 2023-09-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_course_modules_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_modules',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course_modules',
            name='c_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='c_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
