# Generated by Django 4.2.5 on 2023-09-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_domain_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_domain',
            name='phone',
            field=models.JSONField(default=dict),
        ),
    ]
