# Generated by Django 4.2.5 on 2023-09-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_modules_id_alter_course_modules_c_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_modules',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
