# Generated by Django 4.2.5 on 2023-09-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_domain_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_domain',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
