# Generated by Django 4.2.5 on 2023-09-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_company_company_mapping_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='company_subtopic',
            old_name='Company',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='company_subtopic',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='company_subtopic',
            name='c_name',
        ),
    ]
