# Generated by Django 4.2.5 on 2023-09-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_course_students_course_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_students',
            name='last_viewed',
            field=models.DateField(null=True),
        ),
    ]
