# Generated by Django 4.2.5 on 2023-09-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_course_students_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_students',
            name='course_completion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
