# Generated by Django 4.2.5 on 2023-09-15 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_course_tests_c_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_ppa_profiles',
            fields=[
                ('s_profile_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('school_id', models.UUIDField(default=uuid.uuid4)),
                ('tenth_marks', models.FloatField(null=True)),
                ('is_tenth_percentage', models.IntegerField(null=True)),
                ('twelfth_marks', models.FloatField(null=True)),
                ('is_twelfth_percentage', models.IntegerField(null=True)),
                ('diploma_marks', models.FloatField(null=True)),
                ('is_diploma_percentage', models.IntegerField(null=True)),
                ('ug_marks', models.FloatField(null=True)),
                ('is_ug_percentage', models.IntegerField(null=True)),
                ('pg_marks', models.FloatField(null=True)),
                ('is_pg_percentage', models.IntegerField(null=True)),
                ('roll_no', models.CharField(max_length=50, null=True)),
                ('backlogs', models.IntegerField(null=True)),
                ('current_backlogs', models.IntegerField(null=True)),
                ('degree', models.CharField(max_length=50, null=True)),
                ('work_experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course_students',
            name='course_completion',
            field=models.FloatField(default=0),
        ),
    ]
