# Generated by Django 4.2.5 on 2023-09-16 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language_wise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name=uuid.uuid4)),
                ('language_used', models.CharField(max_length=50)),
                ('student_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('MarksPercentage', models.FloatField()),
                ('Hard_correct_questions', models.IntegerField(default=0)),
                ('Easy_correct_questions', models.IntegerField(default=0)),
                ('medium_correct_questions', models.IntegerField(default=0)),
                ('Questions_Correct', models.IntegerField(default=0)),
                ('Questions_wrong', models.IntegerField(default=0)),
                ('Questions_skipped', models.IntegerField(default=0)),
                ('Questions_partial_correct', models.IntegerField(default=0)),
                ('Questions_not_viewed', models.IntegerField(default=0)),
                ('testcase_passed', models.IntegerField(default=0)),
                ('no_of_testcases', models.IntegerField(default=0)),
                ('testcase_percentage', models.FloatField()),
            ],
        ),
    ]
