# Generated by Django 4.2.5 on 2023-09-16 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_wise',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language_wise',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
