# Generated by Django 4.2.5 on 2023-09-16 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentapp', '0006_alter_module_wise_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtopic_wise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('subtopic_name', models.CharField(max_length=50)),
                ('student_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('MarksPercentage', models.FloatField(null=True)),
                ('Hard_correct_questions', models.IntegerField(default=0)),
                ('Easy_correct_questions', models.IntegerField(default=0)),
                ('medium_correct_questions', models.IntegerField(default=0)),
                ('Questions_Correct', models.IntegerField(default=0)),
                ('Questions_wrong', models.IntegerField(default=0)),
                ('Questions_skipped', models.IntegerField(default=0)),
                ('Questions_partial_correct', models.IntegerField(default=0)),
                ('Questions_not_viewed', models.IntegerField(default=0)),
                ('testcase_passed', models.IntegerField(default=0)),
                ('no_of_testcases', models.IntegerField(default=0)),
                ('testcase_percentage', models.FloatField()),
                ('email', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
