# Generated by Django 4.2.5 on 2023-09-17 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_course_students_email_alter_course_students_c_id'),
        ('studentapp', '0007_subtopic_wise'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('total_topics', models.IntegerField(default=0)),
                ('Questions_Correct', models.IntegerField(default=0)),
                ('attended', models.IntegerField(default=0)),
                ('accuracy', models.FloatField()),
                ('company_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('email_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
