# Generated by Django 4.2.5 on 2023-09-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_alter_company_recommendation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_recommendation',
            name='comp',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
